# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
    - dist: precise
      r: 3.2
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode7.3
